project:
  type: website
  output-dir: _site
  
website:
  title: "Chicago Health Networks Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Our Team"
        file: Ourteam.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024"

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 2

